# Generated by Django 5.1.3 on 2024-11-16 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_images_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoItem',
        ),
    ]
