# Generated by Django 5.1.3 on 2024-11-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='gitLink',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='program',
            name='program',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
