# Generated by Django 5.1.3 on 2024-11-18 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_program_gitlink_alter_program_program'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='program',
            new_name='demoLink',
        ),
    ]
