# Generated by Django 5.1.3 on 2024-11-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_rename_program_program_demolink'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='demoLink2',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
